### ISSUE TITLE
Can't find this plugin in Obsidian

### ISSUE THREAD

**Issue by ReinerKnudsen** [SimplGy/obsidian-emoji-magic#1]
Any idea why I can't find this plugin in Obsidian?

**Comment by SimplGy** [comment]
Yeah, I'm waiting for 2nd round [review](https://github.com/obsidianmd/obsidian-releases/pull/1603).

While I've got you, I'm curious -- what feature/aspect made you interested enough in having this particular emoji extension that you created a github issue?

**Comment by ReinerKnudsen** [comment]
I love using emojis and I find the current way to add them neither convenient nor intuitive. Other plugins only provide a limited set of pictures and only a few keywords. So I‘m looking forward to trying out what your plugin does 😀

**Comment by SimplGy** [comment]
Should be there now, @ReinerKnudsen, let me know what you think.
