### ISSUE TITLE
Emoji in the file name with hotkeys

### ISSUE THREAD

**Issue by N0vum** [SimplGy/obsidian-emoji-magic#2]
Nice plugin, thanks!
It would be great to be able to insert emoji into file names with hotkeys. Currently, this can only be done by copying emoji to the clipboard.

**Comment by SimplGy** [comment]
Today it only has  "insert emoji..."

Do emoji go in the front or the end in your filenames?

Considering:

- [ ] 1) add a hotkey for "copy emoji..."
- [ ] 2) add a hotkey for "insert emoji at start of filename..."
- [ ] 3) add a hotkey for "insert emoji at end of filename..."

**Comment by N0vum** [comment]
@SimplGy,
2) add a hotkey for "insert emoji at start of filename..."
![image](https://user-images.githubusercontent.com/61557802/226257392-62768b24-6395-4fb1-86a9-73aba9656ad6.png)
Thanks for the link)

**Comment by SimplGy** [comment]
Resolved by https://github.com/SimplGy/obsidian-emoji-magic/commit/b6ced059dcdda7ba32171b2626ab199c00b2d709

Added a keyboard shortcut command for either "add to filename" or "copy to clipboard". Thanks for the Feature Request.
