### ISSUE TITLE
FR: Autofocus cursor in search box (iOS)

### ISSUE THREAD

**Issue by TinkerSquirrel** [SimplGy/obsidian-emoji-magic#3]
Nice looking plugin so far. I’m using an iPad Pro 2020 with external keyboard so this plugin looks like it will be really helpful for adding emoji with less fuss.

It would be really helpful for the cursor to autofocus in the plugin’s search box after bringing it up with a hotkey. Currently I have to tap in manually.

**Comment by SimplGy** [comment]
I am using the `autofocus` html attr to accomplish this [here](https://github.com/SimplGy/obsidian-emoji-magic/blob/main/src/search_modal.ts#L92).

Must be something related to iOS. Confirming that it ignores `autofocus`... [confirmed](https://medium.com/@brunn/autofocus-in-ios-safari-458215514a5f). Looks like something they make difficult on purpose, though it can probably be worked around.

**Comment by SimplGy** [comment]
gonna close as infeasible. if IOS wants to ignore the `autofocus` attribute, working around that behavior is probably not worth the time or complexity
