### ISSUE TITLE
📅 not appearing in plugin search results

### ISSUE THREAD

**Issue by TinkerSquirrel** [SimplGy/obsidian-emoji-magic#4]
Neither calendar emoji 📅 nor 📆 are currently appearing in the plugin’s search results.

I have searched using the following (rough order of what I would have expected to produce results):
- `cal` and `calendar`
- `da` and `date`
- `red`
- `whi` and `white`
- `num` and `number`

Searching “calendar” suggests 📆 and 📅 in iOS inbuilt emoji search.

**Comment by SimplGy** [comment]
Thanks for the report. especially for the search queries you used.

Should fix, not sure when because I'll have to fix it in the upstream and sync it back down, right now that's kind of a manual process, so want a few more of these broken queries to fix, first.

**Comment by SimplGy** [comment]
Here please, thank you!

If inclined, a format like this is easy for me:

Wanted 🥳. Searched for “purple hat” “fun” “popper” “party”

**Comment by kazerniel** [comment]
Fwiw I'm getting all 3 calendars offered when I search for "cal".

But I have one to report myself:

Wanted 🫠. Searched for "melt"

**Comment by SimplGy** [comment]
calendar was already there; others resolved by https://github.com/SimplGy/emoji-magic/commit/639badd5135490054d823c0c4a0c9d6c25f0a83d

Improving ranking for "cal" would be good, separate issue though.
